### PR TITLE
Support for customisation of the WWW-Authenticate header value to pre…

### PR DESCRIPTION
**Pull request by identityclash**
…vent showing of default browser popup on a 401

### CODE REVIEW

**Comment by hueniverse** [comment]
This makes no sense. This is an HTTP Basic auth scheme and you are asking for it to say it is something else. If you want another scheme, use another scheme.

**Comment by identityclash** [comment]
Hi Eran,

Yes, I understand what you're saying, i.e. to change to a different authentication scheme like Digest, etc. and I've thought about it in that way either after checking other resources; however, there are times when one needs to use the functionality of the basic authentication, but in order to prevent the browser authentication popup from showing up to the user (e.g. assuming when I use Visionary and Handlerbars plugins to display the web pages to the user from the handler instead of returning a JSON response), the returned header "WWW-Authenticate: Basic" may be replaced with something, like "WWW-Authenticate: xBasic" as a workaround; hence, I suggested the flexibility to support a custom-made header for hapi-auth-basic. I understand that this is not standard, but it does give the developer the leeway to tweak hapi-auth-basic similar to the optional configs with Hapi.

Below are some of the resources I referred to when I sought this issue:
https://stackoverflow.com/questions/22170264/hide-basic-authentication-popup-with-jquery-in-chrome
https://github.com/domenic/restify-oauth2/issues/27
https://loudvchar.blogspot.ca/2010/11/avoiding-browser-popup-for-401.html
https://devcentral.f5.com/questions/rewrite-header-quotwww-authenticate-basic-realm-quot
http://wenda.mojijs.com/Home/question/detail/id/9859627/p/1/index.html
https://www.bountysource.com/issues/23443811-prevent-www-authenticate-header

I'm open to suggestions if this is still not a valid case. 

Thanks.

**Comment by hueniverse** [comment]
I say fork it and make the changes you want. It's very little code.

**Comment by identityclash** [comment]
Already done. Thanks.

**Pull request closed without merging**
